### ISSUE TITLE
Refactor widget component as widget that follows Volto's widget conventions

### ISSUE THREAD

**Issue by tiberiuichim** [eea/volto-widget-geolocation#3]
https://github.com/eea/volto-widget-geolocation/blob/3a536eb0081e8493d2dea235c6be923cb704242c/src/components/manage/Widgets/GeolocationWidget.jsx#L23

- Widgets should be controlled components. Ideally they shouldn't have internal state, I don't see any reason why state is used in that component, just to have it immediately synced with onChangeBlock to the parent
- This component is not a widget. Volto widgets have an `onChange` callback, not `onChangeBlock`. See https://github.com/plone/volto/blob/master/src/components/manage/Widgets/UrlWidget.jsx for example.

**Comment by nileshgulia1** [comment]
@tiberiuichim Not using states looks a good thing when it comes to isolated widgets. But when it comes to specific cases like ours, we need a state to handle these things. Yes we can handle those things on a project basis. What I was thinking when building this was it should be built to only adapt to cases like ours.

Nonetheless, I will try to adapt to volto widget conventions and see if that suits our case. Thanks for reporting :)

**Comment by tiberiuichim** [comment]
@nileshgulia1 We're big users of schemas and widgets, I think Alin explained that. If this is a component that can't be integrated with the regular `<Form>` as part of a schema, we can't use it in other projects. If it follows the widgets API then it can be dropped and easily integrated in any of our existing projects.

**Comment by nileshgulia1** [comment]
fixed by #2
